import { Employee, TimeRecord, Holiday, AdminUser } from '../types';

export const BRAZILIAN_HOLIDAYS_2025_2026: Holiday[] = [
  { data: '2025-01-01', nome: 'Confraternização Universal', tipo: 'Nacional' },
  { data: '2025-03-03', nome: 'Carnaval (Segunda)', tipo: 'Nacional' },
  { data: '2025-03-04', nome: 'Carnaval (Terça)', tipo: 'Nacional' },
  { data: '2025-04-18', nome: 'Sexta-feira Santa', tipo: 'Nacional' },
  { data: '2025-04-21', nome: 'Tiradentes', tipo: 'Nacional' },
  { data: '2025-05-01', nome: 'Dia do Trabalho', tipo: 'Nacional' },
  { data: '2025-06-19', nome: 'Corpus Christi', tipo: 'Nacional' },
  { data: '2025-08-02', nome: 'Aniversário de Coari', tipo: 'Municipal', sedeAtingida: 'KO' },
  { data: '2025-09-07', nome: 'Independência do Brasil', tipo: 'Nacional' },
  { data: '2025-10-12', nome: 'Nossa Senhora Aparecida', tipo: 'Nacional' },
  { data: '2025-10-24', nome: 'Aniversário de Manaus', tipo: 'Municipal', sedeAtingida: 'MN' },
  { data: '2025-11-02', nome: 'Finados', tipo: 'Nacional' },
  { data: '2025-11-15', nome: 'Proclamação da República', tipo: 'Nacional' },
  { data: '2025-11-20', nome: 'Dia da Consciência Negra', tipo: 'Nacional' },
  { data: '2025-12-08', nome: 'Nossa Senhora da Conceição (Belém/Manaus)', tipo: 'Estadual', sedeAtingida: 'BE' },
  { data: '2025-12-25', nome: 'Natal', tipo: 'Nacional' },
  { data: '2026-01-01', nome: 'Confraternização Universal', tipo: 'Nacional' },
  { data: '2026-01-12', nome: 'Aniversário de Belém', tipo: 'Municipal', sedeAtingida: 'BE' },
  { data: '2026-02-16', nome: 'Carnaval (Segunda)', tipo: 'Nacional' },
  { data: '2026-02-17', nome: 'Carnaval (Terça)', tipo: 'Nacional' },
  { data: '2026-04-03', nome: 'Sexta-feira Santa', tipo: 'Nacional' },
  { data: '2026-04-21', nome: 'Tiradentes', tipo: 'Nacional' },
  { data: '2026-05-01', nome: 'Dia do Trabalho', tipo: 'Nacional' },
  { data: '2026-06-04', nome: 'Corpus Christi', tipo: 'Nacional' },
  { data: '2026-09-07', nome: 'Independência do Brasil', tipo: 'Nacional' },
  { data: '2026-10-12', nome: 'Nossa Senhora Aparecida', tipo: 'Nacional' },
  { data: '2026-11-02', nome: 'Finados', tipo: 'Nacional' },
  { data: '2026-11-15', nome: 'Proclamação da República', tipo: 'Nacional' },
  { data: '2026-11-20', nome: 'Dia da Consciência Negra', tipo: 'Nacional' },
  { data: '2026-12-25', nome: 'Natal', tipo: 'Nacional' },
];

export const INITIAL_ADMINS: AdminUser[] = [
  {
    id: 'adm-coari',
    email: 'coari.comara@gmail.com',
    nome: 'Coari Comara (Administrador Geral)',
    cargo: 'Gerente Geral de RH / TI',
    funcao: 'Super Administrador TI / RH',
    postoGraduacao: 'Maj',
    nomeGuerra: 'Coari',
    saram: '1000000',
    tituloImpressao: 'Chefe da Seção de Pessoal & TI',
    nivelAcesso: 'SUPER_ADMIN',
    role: 'SUPER_ADMIN',
    status: 'ativo',
    ativo: true,
    sede: 'TODAS',
    canteiroSede: 'TODAS',
    criadoEm: '2025-01-01 08:00:00',
  },
  {
    id: 'adm-comarafab',
    email: 'comarafab@gmail.com',
    nome: 'Super Administrador COMARA FAB',
    cargo: 'Super Administrador TI / RH',
    funcao: 'Super Administrador TI / RH',
    postoGraduacao: 'Cel',
    nomeGuerra: 'COMARA',
    saram: '1000001',
    tituloImpressao: 'Comando / Divisão de Pessoal',
    nivelAcesso: 'SUPER_ADMIN',
    role: 'SUPER_ADMIN',
    status: 'ativo',
    ativo: true,
    sede: 'TODAS',
    canteiroSede: 'TODAS',
    criadoEm: '2026-01-01 08:00:00',
  },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-001',
    matricula: 'MAT-1010',
    nome: 'Carlos Eduardo Silveira',
    funcao: 'Engenheiro de Operações',
    sede: 'KO',
    sede_origem: 'KO',
    sede_atual: 'KO',
    sedeCodigo: 'KO',
    lotacaoUoCodigo: 'DECO_KO',
    uoExecucaoCodigo: 'DECO_KO',
    canteiroExecucaoId: 'canteiro-ko',
    departamentoOriginal: 'DECO-KO',
    dataAdmissao: '2022-03-15',
    status: 'Ativo',
    email: 'carlos.silveira@empresa.com.br',
    telefone: '(97) 98412-3301',
    saldoInicialHoras: 12.5,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    url_foto_perfil: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
  },
  {
    id: 'emp-002',
    matricula: 'MAT-1020',
    nome: 'Juliana Beatriz Mendes',
    funcao: 'Técnica em Eletromecânica',
    sede: 'BE',
    sede_origem: 'BE',
    sede_atual: 'KO', // Exemplo de alocação temporária em Coari
    sedeCodigo: 'KO',
    lotacaoUoCodigo: 'SEDE_BE',
    uoExecucaoCodigo: 'DECO_KO',
    canteiroExecucaoId: 'canteiro-ko',
    departamentoOriginal: 'SEDE-BE',
    dataInicioAlocacao: '2026-02-01',
    dataFimAlocacao: '2026-04-30',
    dataAdmissao: '2021-08-10',
    status: 'Ativo',
    email: 'juliana.mendes@empresa.com.br',
    telefone: '(91) 99123-4567',
    saldoInicialHoras: 4.0,
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    url_foto_perfil: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
  },
  {
    id: 'emp-003',
    matricula: 'MAT-1030',
    nome: 'Rodrigo Albuquerque Dias',
    funcao: 'Supervisor de Logística',
    sede: 'MN',
    sede_origem: 'MN',
    sede_atual: 'MN',
    sedeCodigo: 'MN',
    lotacaoUoCodigo: 'SETOR_DL',
    uoExecucaoCodigo: 'SETOR_DL',
    canteiroExecucaoId: 'canteiro-mn',
    departamentoOriginal: 'DL',
    dataAdmissao: '2020-01-20',
    status: 'Férias',
    dataInicioStatus: '2026-02-15',
    dataFimStatus: '2026-03-16',
    motivoStatus: 'Férias Regulamentares 30 dias (Período Aquisitivo 2024/2025)',
    email: 'rodrigo.dias@empresa.com.br',
    telefone: '(92) 98112-9988',
    saldoInicialHoras: -6.5,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    url_foto_perfil: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
  },
  {
    id: 'emp-004',
    matricula: 'MAT-1040',
    nome: 'Fernanda Martins Costa',
    funcao: 'Analista de Planejamento',
    sede: 'KO',
    sede_origem: 'KO',
    sede_atual: 'KO',
    sedeCodigo: 'KO',
    lotacaoUoCodigo: 'DECO_KO',
    uoExecucaoCodigo: 'DECO_KO',
    canteiroExecucaoId: 'canteiro-ko',
    departamentoOriginal: 'DECO-KO',
    dataAdmissao: '2023-05-02',
    status: 'Ativo',
    email: 'fernanda.costa@empresa.com.br',
    telefone: '(97) 98105-7744',
    saldoInicialHoras: 18.0,
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    url_foto_perfil: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
  },
  {
    id: 'emp-005',
    matricula: 'MAT-1050',
    nome: 'Lucas Vinicius Pinheiro',
    funcao: 'Operador de Estação',
    sede: 'BE',
    sede_origem: 'BE',
    sede_atual: 'BE',
    sedeCodigo: 'BE',
    lotacaoUoCodigo: 'SEDE_BE',
    uoExecucaoCodigo: 'SEDE_BE',
    canteiroExecucaoId: 'canteiro-be',
    departamentoOriginal: 'SEDE-BE',
    dataAdmissao: '2023-11-14',
    status: 'Afastado',
    dataInicioStatus: '2026-02-01',
    dataFimStatus: '2026-03-31',
    motivoStatus: 'Licença Médica INSS',
    email: 'lucas.pinheiro@empresa.com.br',
    telefone: '(91) 98455-1234',
    saldoInicialHoras: -16.0,
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    url_foto_perfil: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
  },
  {
    id: 'emp-006',
    matricula: 'MAT-1060',
    nome: 'Mariana Azevedo Ramos',
    funcao: 'Assistente Administrativo',
    sede: 'MN',
    sede_origem: 'MN',
    sede_atual: 'MN',
    sedeCodigo: 'MN',
    lotacaoUoCodigo: 'SETOR_DA',
    uoExecucaoCodigo: 'SETOR_DA',
    canteiroExecucaoId: 'canteiro-mn',
    departamentoOriginal: 'DA',
    dataAdmissao: '2024-02-01',
    status: 'Ativo',
    email: 'mariana.ramos@empresa.com.br',
    telefone: '(92) 99344-7711',
    saldoInicialHoras: 0.0,
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    url_foto_perfil: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
  },
  {
    id: 'emp-007',
    matricula: 'MAT-1070',
    nome: 'Gabriel Santos Nogueira',
    funcao: 'Mecânico Industrial',
    sede: 'KO',
    sede_origem: 'KO',
    sede_atual: 'KO',
    sedeCodigo: 'KO',
    lotacaoUoCodigo: 'DECO_KO',
    uoExecucaoCodigo: 'DECO_KO',
    canteiroExecucaoId: 'canteiro-ko',
    departamentoOriginal: 'DECO-KO',
    dataAdmissao: '2022-09-18',
    status: 'Ativo',
    email: 'gabriel.nogueira@empresa.com.br',
    telefone: '(97) 98822-1133',
    saldoInicialHoras: 8.5,
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    url_foto_perfil: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
  },
  {
    id: 'emp-008',
    matricula: 'MAT-1080',
    nome: 'Patrícia Rocha Lima',
    funcao: 'Inspetora de Qualidade',
    sede: 'BE',
    sede_origem: 'BE',
    sede_atual: 'BE',
    sedeCodigo: 'BE',
    lotacaoUoCodigo: 'SEDE_BE',
    uoExecucaoCodigo: 'SEDE_BE',
    canteiroExecucaoId: 'canteiro-be',
    departamentoOriginal: 'SEDE-BE',
    dataAdmissao: '2021-04-05',
    status: 'Ativo',
    email: 'patricia.lima@empresa.com.br',
    telefone: '(91) 98177-3322',
    saldoInicialHoras: 22.0,
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    url_foto_perfil: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
  },
];

export const INITIAL_TIME_RECORDS: TimeRecord[] = [
  {
    id: 'rec-001',
    matricula: 'MAT-1010',
    employeeName: 'Carlos Eduardo Silveira',
    employeeSede: 'KO',
    employeeFuncao: 'Engenheiro de Operações',
    dataRegistro: '2026-08-03',
    tipoOcorrencia: 'TRABALHO',
    codigoOcorrencia: 'TRAB',
    horasBrutas: 2.0,
    multiplicador: 1.0,
    saldoCalculado: 2.0,
    eFeriado: false,
    diaSemana: 1,
    diaSemanaNome: 'Segunda-feira',
    observacao: 'Hora extra para suporte na partida do gerador 02',
    criadoEm: '2026-08-03T18:30:00Z',
  },
  {
    id: 'rec-002',
    matricula: 'MAT-1010',
    employeeName: 'Carlos Eduardo Silveira',
    employeeSede: 'KO',
    employeeFuncao: 'Engenheiro de Operações',
    dataRegistro: '2026-08-08',
    tipoOcorrencia: 'TRABALHO',
    codigoOcorrencia: 'TRAB',
    horasBrutas: 4.0,
    multiplicador: 1.5,
    saldoCalculado: 6.0, // 4 * 1.5
    eFeriado: false,
    diaSemana: 6,
    diaSemanaNome: 'Sábado',
    observacao: 'Plantão emergencial de fim de semana (Adicional 50%)',
    criadoEm: '2026-08-08T14:00:00Z',
  },
  {
    id: 'rec-003',
    matricula: 'MAT-1020',
    employeeName: 'Juliana Beatriz Mendes',
    employeeSede: 'BE',
    employeeFuncao: 'Técnica em Eletromecânica',
    dataRegistro: '2026-08-09',
    tipoOcorrencia: 'TRABALHO',
    codigoOcorrencia: 'TRAB',
    horasBrutas: 5.0,
    multiplicador: 2.0,
    saldoCalculado: 10.0, // 5 * 2.0
    eFeriado: false,
    diaSemana: 0,
    diaSemanaNome: 'Domingo',
    observacao: 'Parada programada de manutenção elétrica (Horas em Dobro)',
    criadoEm: '2026-08-09T17:15:00Z',
  },
  {
    id: 'rec-004',
    matricula: 'MAT-1030',
    employeeName: 'Rodrigo Albuquerque Dias',
    employeeSede: 'MN',
    employeeFuncao: 'Supervisor de Logística',
    dataRegistro: '2026-08-04',
    tipoOcorrencia: 'FALTA_INJUSTIFICADA',
    codigoOcorrencia: 'F',
    horasBrutas: 8.0,
    multiplicador: 0.0,
    saldoCalculado: -8.0,
    eFeriado: false,
    diaSemana: 2,
    diaSemanaNome: 'Terça-feira',
    observacao: 'Ausência sem justificativa prévia - desconto de jornada diária',
    criadoEm: '2026-08-04T19:00:00Z',
  },
  {
    id: 'rec-005',
    matricula: 'MAT-1040',
    employeeName: 'Fernanda Martins Costa',
    employeeSede: 'KO',
    employeeFuncao: 'Analista de Planejamento',
    dataRegistro: '2026-08-05',
    tipoOcorrencia: 'ATESTADO_MEDICO',
    codigoOcorrencia: 'AT',
    horasBrutas: 8.0,
    multiplicador: 0.0,
    saldoCalculado: 0.0,
    eFeriado: false,
    diaSemana: 3,
    diaSemanaNome: 'Quarta-feira',
    observacao: 'Atestado médico CID J06 - Consulta e repouso médico homologado pelo SESMT',
    comprovante: {
      id: 'att-001',
      fileName: 'atestado_fernanda_costa_05ago.pdf',
      fileSize: 245100,
      fileType: 'application/pdf',
      driveFileId: '1AbC9dE_FghIjKlmNoPqrStUvWxYz1234',
      driveViewUrl: 'https://drive.google.com/file/d/1AbC9dE_FghIjKlmNoPqrStUvWxYz1234/view',
      uploadTimestamp: '2026-08-05T09:30:00Z',
    },
    criadoEm: '2026-08-05T09:35:00Z',
  },
  {
    id: 'rec-006',
    matricula: 'MAT-1050',
    employeeName: 'Lucas Vinicius Pinheiro',
    employeeSede: 'BE',
    employeeFuncao: 'Operador de Estação',
    dataRegistro: '2026-08-07',
    tipoOcorrencia: 'FALTA_INJUSTIFICADA',
    codigoOcorrencia: 'D',
    horasBrutas: 8.0,
    multiplicador: 0.0,
    saldoCalculado: -8.0,
    eFeriado: false,
    diaSemana: 5,
    diaSemanaNome: 'Sexta-feira',
    observacao: 'Falta sem comprovação - aplicada penalidade de -8h no banco',
    criadoEm: '2026-08-07T18:00:00Z',
  },
  {
    id: 'rec-007',
    matricula: 'MAT-1070',
    employeeName: 'Gabriel Santos Nogueira',
    employeeSede: 'KO',
    employeeFuncao: 'Mecânico Industrial',
    dataRegistro: '2026-08-02',
    tipoOcorrencia: 'TRABALHO',
    codigoOcorrencia: 'TRAB',
    horasBrutas: 6.0,
    multiplicador: 2.0,
    saldoCalculado: 12.0, // 6 * 2.0
    eFeriado: true,
    nomeFeriado: 'Aniversário de Coari',
    diaSemana: 0,
    diaSemanaNome: 'Domingo',
    observacao: 'Feriado Municipal Coari / Horas em dobro autorizadas pela gerência',
    criadoEm: '2026-08-02T16:45:00Z',
  },
  {
    id: 'rec-008',
    matricula: 'MAT-1080',
    employeeName: 'Patrícia Rocha Lima',
    employeeSede: 'BE',
    employeeFuncao: 'Inspetora de Qualidade',
    dataRegistro: '2026-08-11',
    tipoOcorrencia: 'COMPENSACAO',
    codigoOcorrencia: 'COMP',
    horasBrutas: 4.0,
    multiplicador: 1.0,
    saldoCalculado: -4.0,
    eFeriado: false,
    diaSemana: 2,
    diaSemanaNome: 'Terça-feira',
    observacao: 'Folga compensatória parcial previamente acordada',
    criadoEm: '2026-08-11T12:00:00Z',
  },
];
